version: '2'
services:
  service:
    container_name: microservice_name
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/service
    image: prominas/microservice_name
    tty: true
    entrypoint: /bin/bash
