version: '2'
services:
  service:
    container_name: myapp_name
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/service
    image: mytag/myapp_name
    tty: true
    entrypoint: /bin/sh
